roles:
- - mon.a
  - mds.0
  - osd.0
- - mon.b
  - osd.1
- - client.0
tasks:
- install:
     branch: cuttlefish
     extras: yes
- ssh_keys:
- ceph-deploy:
     branch:
        stable: cuttlefish
- ceph-fuse:
- workunit:
     clients:
        client.0:
           - cls/test_cls_rbd.sh
