roles:
- - mon.a
  - mds.a
  - osd.0
  - osd.1
- - mon.b
  - mon.c
  - osd.2
  - osd.3
- - client.0
tasks:
- install:
     branch: cuttlefish
- ceph:
- workunit:
     branch: cuttlefish
     clients:
        client.0:
           - suites/iogen.sh
- install.upgrade:
     all:
        branch: next
- ceph.restart: [mon.a, mon.b, mon.c, mds.a, osd.0, osd.1, osd.2, osd.3]
- workunit:
     branch: next
     clients:
        all: [misc/trivial_sync.sh]
