roles:
- - mon.a
  - mds.a
  - osd.0
  - osd.1
- - mon.b
  - mon.c
  - osd.2
  - osd.3
- - client.0
tasks:
- install:
     branch: bobtail
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      rgw_server: client.0
- install.upgrade:
     all:
        branch: next
- ceph.restart: [mon.a, mon.b, mon.c, mds.a, osd.0, osd.1, osd.2, osd.3]
- swift:
    client.0:
      rgw_server: client.0
