tasks:
- install:
- ceph:
    log-whitelist:
    - wrongly marked me down
    - objects unfound and apparently lost
    conf:
      osd:
        osd debug reject backfill probability: .3
        osd max backfills: 1
- thrashosds:
    timeout: 1200
    chance_pgnum_grow: 1
    chance_pgpnum_fix: 1
